language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: "pip install requests"
# command to run tests
script: python sina_weibo_album_downloader.py